project_id = "uszmpknbnpsenoahivkf"

[api]
enabled = true

[db]
major_version = 17

[functions.creer-utilisateur]
verify_jwt = true

[functions.bootstrap-super-admin]
verify_jwt = false

[functions.inviter-admin]
verify_jwt = true

[functions.get-invitation]
verify_jwt = false

[functions.accepter-invitation]
verify_jwt = false
