// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hclblglvrelkrzbzyxua.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhjbGJsZ2x2cmVsa3J6Ynp5eHVhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0ODIzMDcsImV4cCI6MjA3MzA1ODMwN30.orH3H4ZeUQ2lZ6vH5P78WYxT7MDBTP1Uxn9d7r67inE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});